services:
  postgres:
    image: leogloriainfnet/postgres-tp2-spring:2.0-win
    container_name: api-guilda-postgres
    environment:
      POSTGRES_PASSWORD: jpguild
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  elasticsearch:
    image: leogloriainfnet/elastic-tp2-spring:1.0-alternativo
    container_name: api-guilda-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
  elastic_data: